version: "3.9"

services:
  pgdb:
    image: postgres
    container_name: pgdb
    restart: on-failure
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - env/db.env
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    restart: on-failure
    env_file:
      - env/rabbitmq.env
    ports:
      - "5672:5672"
      - "15672:15672"
  django:
    build: ./backend
    container_name: django
    restart: always
    volumes:
      - ./backend:/usr/src/
    ports:
      - "8000:8000"
    env_file:
      - env/django.env
      - env/db.env
      - env/localstack.env
      - env/rabbitmq.env
    depends_on:
      - pgdb
      - localstack
      - rabbitmq
  fastapi:
    build: ./backend/microservice
    container_name: fastapi
    restart: always
    volumes:
      - ./backend/microservice:/usr/src/
    ports:
      - "8080:8080"
    env_file:
      - env/fastapi.env
      - env/localstack.env
      - env/rabbitmq.env
    depends_on:
      - localstack
      - rabbitmq
  localstack:
    image: localstack/localstack
    container_name: localstack
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "4566:4566"
    env_file:
      - env/django.env
      - env/localstack.env
  celery:
    build: ./backend
    container_name: celery
    restart: on-failure
    command: celery -A innotter worker -l INFO
    tty: true
    stdin_open: true
    volumes:
      - ./backend:/usr/src/
    env_file:
      - env/rabbitmq.env
      - env/django.env
      - env/localstack.env
    depends_on:
      - rabbitmq
  react:
    build: ./frontend
    container_name: react
    restart: always
    volumes:
      - ./frontend:/usr/src/
      - /usr/src/node_modules
    ports:
      - "80:80"
    env_file:
      - env/react.env
    depends_on:
      - django
      - fastapi
  flower:
    image: mher/flower
    container_name: flower
    command: celery flower
    ports:
      - "5555:5555"
    volumes:
      - flower_data:/data
    env_file:
      - env/rabbitmq.env
    depends_on:
      - celery
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: on-failure
    depends_on:
      - pgdb
    env_file:
      - env/db.env
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - '8008:80'
volumes:
  pgdata:
  flower_data:
  pgadmin-data:
