# Generated by Django 5.0.4 on 2024-05-04 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_created_at_user_last_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
    ]
