# Generated by Django 4.1.1 on 2022-10-03 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='image_s3_path',
            new_name='image',
        ),
    ]
