# Generated by Django 4.1.2 on 2022-10-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_alter_page_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
